FROM node:20-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the project files
COPY . .

# Expose port 3000 for the client app
EXPOSE 3000

# Start the client application
CMD ["npm", "run", "dev"]
