version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env  # Server-specific environment variables
    depends_on:
      - postgres
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.local  # Client-specific environment variables
    networks:
      - app-network

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: projectmanagement
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
