import type { Metadata } from "next";
import { Chivo } from "next/font/google";
import "./globals.css";
import DashboardWrapper from "./DashboardWrapper";

const chivo = Chivo({   subsets: ["latin"],
  weight: ["400", "700"], });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={chivo.className}
      >
        <DashboardWrapper>
          {children}
        </DashboardWrapper>
      </body>
    </html>
  );
}
