name: Build and push docker image

on:
  push:
    paths:
      - "server/**"
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: |
          docker build -t krishnadev7/teamtrack-server:latest ./server
          docker push krishnadev7/teamtrack-server:latest

      - name: Set RUN_SEED variable
          # Set the seed flag here; change to "false" if not needed
        run: echo "RUN_SEED=true" >> $GITHUB_ENV

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull krishnadev7/teamtrack-server:latest
            docker stop teamtrack-server || true
            docker rm teamtrack-server || true

            docker run --rm -e DATABASE_URL=${{ secrets.DATABASE_URL }} krishnadev7/teamtrack-server:latest npx prisma migrate deploy

            if [ "${RUN_SEED}" = "true" ]; then
              echo "Running seed..."
              docker run --rm -e DATABASE_URL=${{ secrets.DATABASE_URL }} krishnadev7/teamtrack-server:latest npm run seed
            else
            echo "Skipping seed."
            fi

            docker run -d --name teamtrack-server -p 80:8000 -e DATABASE_URL=${{ secrets.DATABASE_URL }} krishnadev7/teamtrack-server:latest
